{
 "title": "Cloudbees CI Dashboard",
 "description": "Shows basic metrics for a Cloudbees CI deployment on Kubernetes using Prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Node", "query": { "query": "label_values(node)" } },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "Master",
    "query": {
     "query": "label_values(jenkins_job_count_value,service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CloudBees CI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top Two Build Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "topk(2, sum by (service, jenkins_job) (default_jenkins_builds_last_build_duration_milliseconds{service=~\"^$Master\"}))",
     "legendFormat": "{{service}}/{{jenkins_job}}"
    }
   ]
  },
  {
   "title": "Top Two Job Queue Durations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(2, sum by (jenkins_job, service) (jenkins_job_queuing_duration{service=~\"^$Master\"}))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Jenkins health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jenkins_health_check_score{service=~\"^$Master\"}) "
    }
   ]
  },
  {
   "title": "Number of Masters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jenkins_health_check_score{service=~\"^$Master\"}) "
    }
   ]
  },
  {
   "title": "Number of executors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jenkins_executor_free_value{service=~\"^$Master\"})"
    }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (jenkins_job_count_value{service=~\"^$Master\"})"
    }
   ]
  },
  {
   "title": "Currently Running Jobs (in progress)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jenkins_job_scheduled_total{service=~\"^$Master\"}) - sum(jenkins_node_builds_count{service=~\"^$Master\"})"
    }
   ]
  },
  {
   "title": "Total Builds Run",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jenkins_node_builds_count{service=~\"^$Master\"})"
    }
   ]
  },
  {
   "title": "Total Successful Builds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jenkins_runs_success_total{service=~\"^$Master\"})"
    }
   ]
  },
  {
   "title": "Unsuccessful Builds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jenkins_runs_failure_total{service=~\"^$Master\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(jenkins_runs_aborted_total{service=~\"^$Master\"})",
     "legendFormat": "Aborted"
    },
    {
     "expr": "sum(jenkins_runs_unstable_total{service=~\"^$Master\"})",
     "legendFormat": "Unstable"
    }
   ]
  },
  {
   "title": "Jenkins queue size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jenkins_queue_size_value{service=~\"^$Master\"})"
    }
   ]
  },
  { "title": "Utilization Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "JVM CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(vm_cpu_load{service=~\"^$Master\"})"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(vm_memory_total_used{service=~\"^$Master\"})"
    }
   ]
  },
  {
   "title": "JVM Free memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(vm_memory_total_max{service=~\"^$Master\"}) - sum(vm_memory_total_used{service=~\"^$Master\"})) / sum(vm_memory_total_max{service=~\"^$Master\"}) * 100.0"
    }
   ]
  },
  {
   "title": "Cluster Filesystem Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (node_filesystem_size_bytes{node=~\"^$Node$\"}) - sum (node_filesystem_free_bytes{node=~\"^$Node$\"}) )/ sum (node_filesystem_size_bytes{node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (node_memory_MemTotal_bytes{node=~\"^$Node$\"}) - sum (node_memory_MemFree_bytes{node=~\"^$Node$\"})) / sum (node_memory_MemTotal_bytes{node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - sum(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) / sum(rate(node_cpu_seconds_total[5m]))) * 100"
    }
   ]
  },
  { "title": "CI Usage HeatMap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total Builds Run",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(jenkins_job_count_history_count{service=~\"^$Master\"})",
     "legendFormat": "Job Runs"
    }
   ]
  },
  { "title": "Resource Usage Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Network I/O pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[$interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[$interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Pods network I/O ($interval avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{node=~\"^$Node$\"}[$interval])) by (pod)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{node=~\"^$Node$\"}[$interval])) by (pod)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{node=~\"^$Node$\"}) by (pod)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pods CPU usage ($interval avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{node=~\"^$Node$\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}